### ISSUE TITLE
Let // => have continuations

### ISSUE THREAD

**Issue by ianb** [ianb/doctestjs#31]
Right now you can't do:

``` javascript
example()
// => line 1
// line 2
```

Instead you must do:

``` javascript
example()
/* => line 1
line 2 */
```

`//` is sometimes nicer, especially if you have to continue the line or something.  Maybe detect lines with // that are adjacent?

**Comment by boxed** [comment]
In my pull request (41), I have a code for this issue, with the syntax:

// => line 1
// => line 2

**Comment by boxed** [comment]
Hmm, why didn't github close this issue automatically?
