### ISSUE TITLE
How is it different from `assert.deepEqual`

### ISSUE THREAD

**Issue by Raynos** [ianb/doctestjs#33]
You can just replace all your print statements with assert.deepEqual and it would work.

If you wanted you could even write a clever equal function to do the pattern matching you wanted.

What warrants including an entire parser and doing crazy comment parsing?

**Comment by ianb** [comment]
Using something like several Spies you can test a sequence of actions, not just a single action.  The wildcard support is at least _different_ from what deepEqual does, it's up to taste if you think it's better.

Obviously there's nothing in doctest.js you couldn't do in other systems – and ultimately you could write something like doctest into your unit tests.

**Comment by Raynos** [comment]
@ianb can you make some good examples about why describing results in comments is superior to describing results in code.

I really like the doctest idea. (enough to make my own attempt ( https://github.com/Raynos/doc-test ))

Could you go into more detail on the multiple spies thing?

**Comment by ianb** [comment]
Is this a suggestion that I describe the advantages of output in comments in the docs?

**Comment by Raynos** [comment]
@ianb it's not obvious how 

```
print(foo)
// pattern
```

is better then `similar(foo, "pattern")` other then minor style preferences. I'm attracted to the idea because of the style thing. I can't think of concrete / real advantages.
