### ISSUE TITLE
Loading of section-less external .js fails silently

### ISSUE THREAD

**Issue by shamrin** [ianb/doctestjs#42]
Pull request #41 broke loading of external files without sections. E.g. examples-2.js silently fails to load in examples/examples-2.html.

**Comment by shamrin** [comment]
@boxed, thank you! I'm now able to appreciate your earlier changes (total number of tests, removal of annoying `\n` before the output) :-)

**Comment by boxed** [comment]
@shamrin no problem, glad you like the changes :P
