### ISSUE TITLE
doctestjs not running on IE8

### ISSUE THREAD

**Issue by lloyd** [ianb/doctestjs#5]
title says it all

**Comment by lloyd** [comment]
The basic work of porting to IE is addressed here:

http://github.com/lloyd/doctestjs/commit/37dd01e71c14f313f7055eb9c6a251202e6a410c

After pulling this, there's two main areas left:
1. line endings!  rendering is screwed up in IE after running tests (\n doesn't cause proper line breaking in pre tags in IE)
2. more line endings!  multiline tests are broken ($ followed by >)

**Comment by ianb** [comment]
Everything has changed a lot since then.  But I'm sure it's all broken in IE :(  Still, I suppose current breakage should just be its own ticket.
